boo_silev/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
]

core/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^core/$', views.page_first, name='page_first'),
    url(r'^core/create-user/$', views.create_user_view, name='create_user'),
    url(r'^core/login-user/$', views.login_view, name='login_user'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django.contrib.auth.models import User
from django import forms
from . import models


class CreateUser(forms.Form):
    username = forms.CharField(label='Имя пользователя',
                               max_length=100,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='Пароль',
                                max_length=50,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='Подтвердите пароль',
                                max_length=50,
                                widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    email = forms.CharField(label='Адрес электронной почты',
                            max_length=50,
                            required=True,
                            widget=forms.EmailInput(attrs={'class': 'form-control'}))

    def clean(self):
        cleaned_data = super().clean()
        passwd_1 = cleaned_data.get('password1')
        passwd_2 = cleaned_data.get('password2')

        if passwd_1 and passwd_2 and passwd_1 != passwd_2:
            self.add_error('password1', 'Пароли не совпадают')
            self.add_error('password2', 'Пароли не совпадают')
        return cleaned_data


class LoginUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'password')

core/views.py
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User


def index(request):

    return render(request, 'page_first.html')


def page_first(request):

    return render(request, 'page_first.html')


def create_user_view(request):
    form = forms.CreateUser(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data['username'],
                                            email=form.cleaned_data['email'],
                                            password=form.cleaned_data['password1'])
            user.save()
            return redirect('core:login_user')
    return render(request, 'create_user_form.html', locals())


def login_view(request):
    form = forms.LoginUserForm(request.POST or None)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('core:index')

    return render(request, 'login_user_form.html', locals())

core/templates/create_user_form.html
{% extends 'layout.html' %}

{% block content %}
    <form class="form-horizontal" method="post" novalidate="novalidate">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-lg-2 col-sm-10">
                {{ form.username.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ form.username }}
                {% if form.username.errors %}
                    {{ form.username.errors }}
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-2 col-sm-10">
                {{ form.password1.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ form.password1 }}
                {% if form.password1.errors %}
                    {{ form.password1.errors }}
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-2 col-sm-10">
                {{ form.password2.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ form.password2 }}
                {% if form.password2.errors %}
                    {{ form.password2.errors }}
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-2 col-sm-10">
                {{ form.email.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ form.email }}
                {% if form.email.errors %}
                    {{ form.email.errors }}
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Зарегистрировать</button>
            </div>
        </div>
    </form>
{% endblock %}

core/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>boo_silev</title>

    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

</head>
<body>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <div class="page-header">
                <a href="{% url 'core:index' %}" class="btn btn-success">Главная</a>
                {% if user.is_authenticated %}
                    Пользователь: {{ user.username }}
                {% else %}
                    <a href="{% url 'core:login_user' %}" class="btn btn-success">Войти</a>
                    <a href="{% url 'core:create_user' %}" class="btn btn-primary">Регистрация</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% block content %}{% endblock %}
</div>

</body>
</html>

core/templates/login_user_form.html
{% extends 'layout.html' %}

{% block content %}
    <form class="form-horizontal" method="post" novalidate="novalidate">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-lg-2 col-sm-10">
                {{ form.username.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ form.username }}
                {% if form.username.errors %}
                    {{ form.username.errors }}
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-2 col-sm-10">
                {{ form.password.label }}
            </div>
            <div class="col-lg-5 col-sm-10">
                {{ form.password }}
                {% if form.password.errors %}
                    {{ form.password.errors }}
                {% endif %}
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Зарегистрировать</button>
            </div>
        </div>
    </form>
{% endblock %}

core/templates/page_first.html
{% extends 'layout.html' %}

{% block content %}
    <h3>Page first</h3>
{% endblock %}